### ISSUE TITLE
Server package test failed

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/paid-qa#571]
Output:

 > FAIL  src/services/tests/main.test.js
  ● Test suite failed to run

>    Cannot find module '../../topic.service' from 'src/services/tests/parts/topic.service.js'

    Require stack:
      src/services/tests/parts/topic.service.js
      src/services/tests/main.test.js

    > 1 | const { createTopic, getTopic, addAppendant } = require("../../topic.service");
        |                                                 ^
      2 |
      3 | jest.mock("../../node.service");
      4 | jest.mock("../../ipfs.service");

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/services/tests/parts/topic.service.js:1:49)

**Comment by wliyongfeng** [comment]
Server package test still failed.
