### ISSUE TITLE
Scan duplicated key

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/paid-qa#679]
> 2022-06-27 13:54 +00:00: MongoServerError: E11000 duplicate key error collection: review-paid-qa-wnd-scan-1.resolves index: topicCid_1_sponsorPublicKey_1 dup key: { topicCid: "bafybeihhhrb6eejfuledpd46nqftqke6jcyctsrna3m77djaxf4gfpd4j4", sponsorPublicKey: "6a6ae53d55eb98a287aec2ca867f67356a7bc7b2d37f3cb48786633b28dd1250" }
2022-06-27 13:54 +00:00:     at /opt/qa/scan/wnd/node_modules/mongodb/lib/operations/insert.js:53:33
2022-06-27 13:54 +00:00:     at /opt/qa/scan/wnd/node_modules/mongodb/lib/cmap/connection_pool.js:277:25
2022-06-27 13:54 +00:00:     at /opt/qa/scan/wnd/node_modules/mongodb/lib/sdam/server.js:212:17
2022-06-27 13:54 +00:00:     at handleOperationResult (/opt/qa/scan/wnd/node_modules/mongodb/lib/sdam/server.js:335:20)
2022-06-27 13:54 +00:00:     at Connection.onMessage (/opt/qa/scan/wnd/node_modules/mongodb/lib/cmap/connection.js:222:9)
2022-06-27 13:54 +00:00:     at MessageStream.<anonymous> (/opt/qa/scan/wnd/node_modules/mongodb/lib/cmap/connection.js:63:60)
2022-06-27 13:54 +00:00:     at MessageStream.emit (node:events:537:28)
2022-06-27 13:54 +00:00:     at processIncomingData (/opt/qa/scan/wnd/node_modules/mongodb/lib/cmap/message_stream.js:132:20)
2022-06-27 13:54 +00:00:     at MessageStream._write (/opt/qa/scan/wnd/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
2022-06-27 13:54 +00:00:     at writeOrBuffer (node:internal/streams/writable:392:12) {
2022-06-27 13:54 +00:00:   index: 0,
2022-06-27 13:54 +00:00:   code: 11000,
2022-06-27 13:54 +00:00:   keyPattern: { topicCid: 1, sponsorPublicKey: 1 },
2022-06-27 13:54 +00:00:   keyValue: {
2022-06-27 13:54 +00:00:     topicCid: 'bafybeihhhrb6eejfuledpd46nqftqke6jcyctsrna3m77djaxf4gfpd4j4',
2022-06-27 13:54 +00:00:     sponsorPublicKey: '6a6ae53d55eb98a287aec2ca867f67356a7bc7b2d37f3cb48786633b28dd1250'
2022-06-27 13:54 +00:00:   },
2022-06-27 13:54 +00:00:   [Symbol(errorLabels)]: Set(0) {}
2022-06-27 13:54 +00:00: }

**Comment by wliyongfeng** [comment]
6172204c17c06fb2b228dda2b5254fcbb472dee7, part work
