### ISSUE TITLE
Scan error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/paid-qa#680]
> RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
    at flattenObjectWithDottedPaths (/Users/mac/work/os/projects/paid-qa/node_modules/mongoose/lib/helpers/path/flattenObjectWithDottedPaths.js:20:23)
    at flattenObjectWithDottedPaths (/Users/mac/work/os/projects/paid-qa/node_modules/mongoose/lib/helpers/path/flattenObjectWithDottedPaths.js:36:5)
    at flattenObjectWithDottedPaths (/Users/mac/work/os/projects/paid-qa/node_modules/mongoose/lib/helpers/path/flattenObjectWithDottedPaths.js:36:5)
    at flattenObjectWithDottedPaths (/Users/mac/work/os/projects/paid-qa/node_modules/mongoose/lib/helpers/path/flattenObjectWithDottedPaths.js:36:5)
    at flattenObjectWithDottedPaths (/Users/mac/work/os/projects/paid-qa/node_modules/mongoose/lib/helpers/path/flattenObjectWithDottedPaths.js:36:5)
    at flattenObjectWithDottedPaths (/Users/mac/work/os/projects/paid-qa/node_modules/mongoose/lib/helpers/path/flattenObjectWithDottedPaths.js:36:5)
    at flattenObjectWithDottedPaths (/Users/mac/work/os/projects/paid-qa/node_modules/mongoose/lib/helpers/path/flattenObjectWithDottedPaths.js:36:5)
    at flattenObjectWithDottedPaths (/Users/mac/work/os/projects/paid-qa/node_modules/mongoose/lib/helpers/path/flattenObjectWithDottedPaths.js:36:5)
    at flattenObjectWithDottedPaths (/Users/mac/work/os/projects/paid-qa/node_modules/mongoose/lib/helpers/path/flattenObjectWithDottedPaths.js:36:5)

Please try westmint block 2009538. The fund interaction handling caused this error.

**Comment by wliyongfeng** [comment]
Fixed in 817cbb00bcc6b6d3dfadf7e8521cf2f1d5a018b2
